config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create', as: 'users'
  root to: 'homes#top'
  get 'homes/myknow' => 'homes#myknow', as: 'myknow'
  
  resources :users, only: [:show, :new, :create, :index, :edit, :update] do
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :groups do
    resources :applies, only: [:index, :create, :destroy]
    resources :knowledges, except: [:new] do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :group_users, only: [:create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'enter'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlp

end

app/models/apply.rb
class Apply < ApplicationRecord
   # アソシエーション
  belongs_to :user
  belongs_to :group

  # バリデーション
  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :user_id, uniqueness: { scope: :group_id }
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :knowledge
  
  validates :user_id, uniqueness: {scope: :knowledge_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge

  # バリデーション
  validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
   # アソシエーション
  belongs_to :room
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :applies, dependent: :destroy
  attachment :image
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  
  validates :content, presence: true
  
  # current_userがブックマークしているかそうでないかでviewを変える
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # アソシエーション
  belongs_to :room
  belongs_to :user

  # バリデーション
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
   # アソシエーション
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  validates :mail, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :knowledges, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favoites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

   attachment :image
   
    # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す機能
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローする/外すボタンの表示を分けるための記載
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  def create
    current_user.applies.create(group_id: apply_params[:group_id])
    flash[:notice] = "You applied to join the group."
    redirect_to request.referer
  end

  # グループ加入申請の拒否と取り消し
  def destroy
    @apply = Apply.find(params[:id])
    @apply.destroy
    flash[:notice] = "You canceled the application."
    redirect_to request.referer
  end

  # 申請をしてグループリーダーの承認を待っているユーザーの一覧
  def index
    @applies = Apply.where(group_id: params[:group_id])
  end

  private

  def apply_params
    params.permit(:group_id)
  end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applies/index.html.erb
<div class="container my-3">
  <h2>Waiting User</h2>
  <% if @applies.present? %>
    <div class="table-responsive">
      <table class="table-hover text-nowrap center">
        <thead>
          <tr>
            <th>Name</th>
            <th>Follows</th>
            <th>Followers</th>
            <th>Follow/Unfollow</th>
            <th>Introduction</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @applies.each do |app| %>
            <tr>
              <td>
              <%= link_to user_path(app.user) do %>
                 <%= attachment_image_tag app.user, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "60x60"%>
                 <%= app.user.name %>
              <% end %>
              </td>
              <td>
                Follows: <%= link_to user_followings_path(app.user) do %><%= app.user.followings.count %><% end %>
              </td>
              <td>
                Followers: <%= link_to user_followers_path(app.user) do %><%= app.user.followers.count %><% end %>
              </td>
              <td class="text-center">
                <% if app.user != current_user %>
                  <% if current_user.following?(app.user) %>
                    <%= link_to "Unfolow", user_relationships_path(app.user), method: :delete, class: 'btn btn-danger' %>
                  <% else %>
                    <%= link_to "Follow", user_relationships_path(app.user), method: :post, class: 'btn btn-primary'%>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if app.user.introduction.present? %>
                  <%= app.user.introduction.truncate(30) %>
                <% end %>
              </td>
              <td>
                <%= link_to "承認", group_users_path(group_id: app.group_id, user_id: app.user_id, apply_id: app.id), method: :post, class: 'btn btn-success' %>
                <%= link_to "却下", group_apply_path(app.group, app), method: :delete, class: 'btn btn-danger text-line-none' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
  <p>承認待ちユーザーはいません。</p>
  <% end %>
</div>