config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create', as: 'users'
  root to: 'homes#top'
  get 'homes/myknow' => 'homes#myknow', as: 'myknow'
  
  resources :users, only: [:show, :new, :create, :index, :edit, :update] do
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :groups do
    resources :applies, only: [:index, :create, :destroy]
    resources :knowledges, except: [:new] do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :group_users, only: [:create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'enter'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlp

end

app/models/apply.rb
class Apply < ApplicationRecord
   # アソシエーション
  belongs_to :user
  belongs_to :group

  # バリデーション
  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :user_id, uniqueness: { scope: :group_id }
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :knowledge
  
  validates :user_id, uniqueness: {scope: :knowledge_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge

  # バリデーション
  validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
   # アソシエーション
  belongs_to :room
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :applies, dependent: :destroy
  attachment :image
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  
  validates :content, presence: true
  
  # current_userがブックマークしているかそうでないかでviewを変える
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # アソシエーション
  belongs_to :room
  belongs_to :user

  # バリデーション
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
   # アソシエーション
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  validates :mail, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :knowledges, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favoites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

   attachment :image
   
    # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す機能
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローする/外すボタンの表示を分けるための記載
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
# グループ作成者でないと、そのグループの編集をできないようにする
  def ensure_current_user
    @group = Group.find(params[:id])
    if current_user.id != @group.leader_id
      flash[:notice] = "Not authorized"
      redirect_to root_path
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.leader_id = current_user.id
    @group.save
    group_user = GroupUser.new
    group_user.user_id = current_user.id
    group_user.group_id = @group.id

    if group_user.save
      redirect_to user_path(current_user), notice: 'You have made new group.'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    if @group.save
      flash[:notice] = "You have updated group successfully."
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def show
    # 表示するべきグループがあれば詳細画面を表示
    if Group.exists?(params[:id])
      @group = Group.find(params[:id])
      @leader = User.find_by(id: @group.leader_id)
      # 承認があればグループリーダーの画面に承認待ち一覧へのボタンを設置
      @applies = Apply.where(group_id: params[:id])
      # グループへの加入申請をしていればキャンセルボタンを設置
      @apply = Apply.find_by(group_id: @group.id, user_id: current_user.id)
      # 所属ユーザー一覧表示
      @group_users = GroupUser.where(group_id: @group.id)
      @users = []
      @group_users.each do |group_user|
        user = User.find_by(id: group_user.user_id)
        @users.push(user)
      end
      @users = Kaminari.paginate_array(@users).page(params[:page]).per(20)
    else
      # グループを削除したことにより表示できない場合はグループ一覧に遷移
      redirect_to groups_path
    end
  end

  def index
    @groups = Group.all.order(created_at: "DESC").page(params[:page]).per(20)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to request.referer
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_index.html.erb
<% if groups.present? %>
<div class="table-responsive">
  <table class="my-3 table-hover text-nowrap center">
    <thead>
      <tr>
        <th>Name</th>
        <th>Introduction</th>
        <th>Details</th>
      </tr>
    </thead>

    <tbody>
      <% groups.each do |group| %>
        <tr>
          <td>
            <!--ログイン中のユーザーがグループに所属しているなら、グループのフレーズ一覧へのリンクにする-->
            <% if GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
              <%= link_to group_knowledges_path(group) do %>
                <%= attachment_image_tag group, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "60x60"%>
                <%= group.name %>
              <% end %>
            <% else %>
                <%= attachment_image_tag group, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "60x60"%>
                <%= group.name %>
            <% end %>
          </td>
          <td>
            <%= group.introduction.truncate(30) %>
          </td>
          <td>
            <%= link_to group_path(group) do %>
            <span>Details</span>
            <% end %>
          </td>
          <td>
            <% if group.leader_id == current_user.id %>
              <%= link_to "Edit", edit_group_path(group), class: 'btn btn-primary' %>
            <% else %>
              <!--退出のリンクへ飛ぶためにIDを定義-->
              <% if GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
                <% group_user = GroupUser.find_by(group_id: group.id, user_id: current_user.id) %>
                <% id = group_user.id %>
              <% end %>
              <% if GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
                <%= link_to "leave", group_user_path(id: id, group_id: group.id), method: :delete, class: 'btn btn-danger' %>
              <% end %>
            <% end %>
          </td>
          <% if group.leader_id == current_user.id %>
            <td>
              <%= link_to "Delete", group_path(group), data: {confirm: "本当に削除しますか？"}, method: :delete, class: 'btn btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/groups/index.html.erb
<div class="container my-3">
  <h2>Group</h2>
  <%= link_to "Make new group", new_group_path, class: "btn btn-success" %>
  <%= render "index", groups: @groups %>
</div>

app/views/groups/new.html.erb
<div class="container my-3">
  <h2>New Group</h2>

  <%= form_with model:@group,local:true do |f| %>
    <%= render 'layouts/errors', model: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction %>
      <%= f.text_field :introduction, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.attachment_field :image %>
    </div>
    <div>
      <%= f.submit "Make Group", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
   
<div class="container my-3">
  <h2>Group detail</h2>
  <!--グループの情報-->
  <div class="text-center">
    <%= attachment_image_tag @group, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "80x80"%>

    <table class="my-3 center">
      <tbody>
        <tr>
          <th>Name</th>
          <td><%= @group.name %></td>
        </tr>
        <tr>
          <th>Introduction</th>
          <td><%= @group.introduction %></td>
        </tr>
        <tr>
          <th>Leader</th>
          <td><%= link_to @leader.name, user_path(@leader) %></td>
        </tr>
      </tbody>
    </table>

    <!--退出のリンクへ飛ぶためにIDを定義-->
     <% if GroupUser.exists?(group_id: @group.id, user_id: current_user.id) %>
      <% group_user = GroupUser.find_by(group_id: @group.id, user_id: current_user.id) %>
      <% id = group_user.id %>
     <% end %>
    <% if @group.leader_id != current_user.id %>
      <!--グループリーダーでなく、GroupUserが存在するなら退会ボタン-->
      <% if GroupUser.exists?(group_id: @group.id, user_id: current_user.id) %>
        <%= link_to "Leave", group_user_path(id: id, group_id: @group.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <!--グループリーダーでなく、GroupUserがないなら、申請の有無で承認機能のボタンを設置-->
        <% if @apply %>
          <%= link_to 'Cancel', group_apply_path(@group, @apply), method: :delete, class: 'btn btn-danger text-line-none' %>
        <% else %>
          <%= link_to 'Apply', group_applies_path(@group), method: :post, class: 'btn btn-success text-line-none' %>
        <% end %>
      <% end %>
    <% else %>
      <!--グループリーダーであり、参加承認待ちのユーザーがいるのであれば、その一覧へのリンクを設置-->
      <% if @applies.present? %>
        <%= link_to "Waiting User", group_applies_path(@group), class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "Edit", edit_group_path(@group), class: 'btn btn-primary' %>
      <%= link_to "Delete", group_path(@group), data: {confirm: "本当に削除しますか？"}, method: :delete, class: 'btn btn-danger' %>
    <% end %>
  </div>
  <!--メンバー一覧-->
  <div class="my-3">
    <h2>Member</h2>
    <%= render 'users/index', users: @users %>
  </div>
</div>