config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create', as: 'users'
  root to: 'homes#top'
  get 'homes/myknow' => 'homes#myknow', as: 'myknow'
  
  resources :users, only: [:show, :new, :create, :index, :edit, :update] do
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :groups do
    resources :applies, only: [:index, :create, :destroy]
    resources :knowledges, except: [:new] do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :group_users, only: [:create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'enter'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlp

end

app/models/apply.rb
class Apply < ApplicationRecord
   # アソシエーション
  belongs_to :user
  belongs_to :group

  # バリデーション
  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :user_id, uniqueness: { scope: :group_id }
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :knowledge
  
  validates :user_id, uniqueness: {scope: :knowledge_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge

  # バリデーション
  validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
   # アソシエーション
  belongs_to :room
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :applies, dependent: :destroy
  attachment :image
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  
  validates :content, presence: true
  
  # current_userがブックマークしているかそうでないかでviewを変える
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # アソシエーション
  belongs_to :room
  belongs_to :user

  # バリデーション
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
   # アソシエーション
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  validates :mail, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :knowledges, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favoites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

   attachment :image
   
    # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す機能
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローする/外すボタンの表示を分けるための記載
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    # 以下所属グループ一覧の記述
    @group_users = GroupUser.where(user_id: @user.id)
    @groups = []
    @group_users.each do |group_user|
      group = Group.find_by(id: group_user.group_id)
      @groups.push(group)
    end
    
    # 以下DM機能の記述
    # ログインしているユーザーが誰とDMでつながっているかを取得
    @currentUserEntry = Entry.where(user_id: current_user.id)
    # 表示しているユーザーが誰とDMでつながっているかを取得する
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      # 上の2つで取得したデータから、重複するroom番号があれば、ルームは存在し、そのidを付与する
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            # falseの時にroomを作成するための記述
            @isRoom = true
            @roomId = cu.room.id
          end
        end
      end
      # ルームがなければ(この画面に遷移した時にDMの部屋が存在しない場合)、それを作るための記述
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated your infomation successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  
  private
    def user_params
      params.permit(:name, :mail)
    end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% if users.present? %>
  <div class="table-responsive">
    <table class="table-hover text-nowrap center">
      <thead>
        <tr>
          <th>Name</th>
          <th>Introduction</th>
          <th>Button</th>
        </tr>
      </thead>
      
      <tbody>
        <% users.each do |user|%>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "60x60"%>
                <%= user.name %>
              <% end %>
            </td>
        
            <td>
              <% if user.introduction.present? %>
                <%= user.introduction.truncate(30) %>
              <% end %>
            </td>
            
            <td>
               <% if user != current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to "Unfolow", user_relationships_path(user), method: :delete, class: 'btn btn-danger' %>
                <% else %>
                  <%= link_to "Follow", user_relationships_path(user), method: :post, class: 'btn btn-primary'%>
                <% end %>
              <% end %>
            </td>
            

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container my-3">
  <h2>User Edit</h2>

  <%= form_with model:@user, local:true do |f| %>
    <%= render 'layouts/errors', model: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction %>
      <%= f.text_field :introduction, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.attachment_field :image %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-success' %>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="container">
  <h2>Sign up</h2>
  <%= form_with url: users_path do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :mail %><br>
    <%= f.text_field :mail %><br>


    <%= f.submit "登録" %>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="container my-3">
  <% if @user == @current_user %>
    <h2>Your Page</h2>
  <% else %>
    <h2><%= @user.name %>'s Page</h2>
  <% end %>
  
  <div class="text-center">
    <%= attachment_image_tag @user, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "80x80"%>
     <table class="my-3 center">
      <tbody>
        <tr>
          <th>Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>Introduction</th>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <th>Follows</th>
          <td><%= link_to user_followings_path(@user) do %><%= @user.followings.count %><% end %></td>
        </tr>
        <tr>
          <th>Followers</th>
          <td><%= link_to user_followers_path(@user) do %><%= @user.followers.count %><% end %></td>
        </tr>
      </tbody>
    </table>
    <div class="my-3 ", style="display: flex; justify-content: center;">
      <% if @user != current_user %>
       　<!--フォロー登録のボタン-->
        <div class="text-center">
          <% if current_user.following?(@user) %>
          　<%= link_to "Unfolow", user_relationships_path(@user), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to "Follow", user_relationships_path(@user), method: :post, class: 'btn btn-primary'%>
          <% end %>
        </div>
      　<!--DMのためのボタン-->
      　<div>
          <% if (current_user.following?(@user)) && (@user.following?(current_user)) %>
            <% if @isRoom == true %>
              <a href="/rooms/<%= @roomId %>" class="btn btn-primary">Chat</a>
            <% else %>
              <!--Chatボタンを初めて押してRoomを作るとき、その情報をroom/createに送信する-->
              <%= form_for @room do |f| %>
                <!--最初にChatボタンを押した人のidがRoomのuser_idになる-->
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= fields_for @entry do |e| %>
                <!--Room作成と同時に相手ユーザー情報もEntryに保存するため、送信-->
                  <%= e.hidden_field :user_id, value: @user.id %>
                <% end %>
                <%= f.submit "Chat", class: 'btn btn-primary user-show-chat'%>
              <% end %>
            <% end %>
          <% end %>
      　</div>
      <% end %>
    </div>
  </div>
  
  <div class="my-3 text-center">
    <% if @user == current_user %>
      <%= link_to "Edit", edit_user_path(@user), class: 'btn btn-primary' %>
      <%= link_to "Make new group", new_group_path, class: 'btn btn-success' %>
    <% end %>
  </div>
  
  <% if @user == current_user %>
    <h2>Your Group</h2>
  <% else %>
    <h2><%= @user.name %>'s Group</h2>
  <% end %>
  <% if @groups.present?%>
    <%= render 'groups/index', groups: @groups %>
  <% else %>
    <p>グループを作成しましょう。</p>
  <% end %>
</div>