config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create', as: 'users'
  root to: 'homes#top'
  get 'homes/myknow' => 'homes#myknow', as: 'myknow'
  
  resources :users, only: [:show, :new, :create, :index, :edit, :update] do
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'followings' => 'relationships#followings', as: 'followings'
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :groups do
    resources :applies, only: [:index, :create, :destroy]
    resources :knowledges, except: [:new] do
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  resources :group_users, only: [:create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'enter'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlp

end

app/models/apply.rb
class Apply < ApplicationRecord
   # アソシエーション
  belongs_to :user
  belongs_to :group

  # バリデーション
  validates :user_id, presence: true
  validates :group_id, presence: true
  validates :user_id, uniqueness: { scope: :group_id }
  validates :group_id, uniqueness: { scope: :user_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :knowledge
  
  validates :user_id, uniqueness: {scope: :knowledge_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge

  # バリデーション
  validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
   # アソシエーション
  belongs_to :room
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :knowledge
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :applies, dependent: :destroy
  attachment :image
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  
  validates :content, presence: true
  
  # current_userがブックマークしているかそうでないかでviewを変える
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # アソシエーション
  belongs_to :room
  belongs_to :user

  # バリデーション
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
   # アソシエーション
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  validates :mail, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :knowledges, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favoites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

   attachment :image
   
    # フォロー機能
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す機能
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローする/外すボタンの表示を分けるための記載
  def following?(user)
    followings.include?(user)
  end
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #808080;">
      <div class="container">
        <!--ロゴ-->
         <%= link_to "Our Know", root_path, class: "col-2 text-light" %>
        <!--ナビバー-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <!--ユーザーログイン時-->
            <% if @current_user %>
              <li style="white-space: nowrap;">
                <%= link_to " My page", user_path(@current_user.id), class:"fas fa-user nav-link text-light text-center" %>
              </li>
              <li style="white-space: nowrap;">
                <%= link_to " Group", groups_path, class:"fas fa-users nav-link text-light text-center" %>
              </li>
              <li style="white-space: nowrap;">
                <%= link_to " Bookmark", myknow_path, class:"fas fa-star nav-link text-light text-center" %>
              </li>
              <li style="white-space: nowrap;">
                <%= link_to " Log out", logout_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light text-center" %>
              </li>
            <% else %>
              <li style="white-space: nowrap;">
                <%= link_to " Sign up", signup_path, class:"fas fa-user-plus nav-link text-light text-center" %>
              </li>
              <li style="white-space: nowrap;">
                <%= link_to " Log in", login_path, class:"fas fa-sign-in-alt nav-link text-light text-center" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurKnow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>